[package]
name = "elk"
version = "0.1.0"
authors = ["scratchyone <scratchywon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.12.0"
codespan-reporting = "0.11.1"
colour = "0.5.0"
